# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='profile_picture',
            new_name='profile_pic',
        ),
    ]
